version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-vpn2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1brrypp04xsan"
s3_prefix = "api-vpn2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []